name: Daily Product Hunt Bot

on:
  # 每天 UTC 时间 1:00 运行（北京时间 9:00）
  schedule:
    - cron: '0 1 * * *'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: 安装依赖
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 运行机器人
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        PH_TOKEN: ${{ secrets.PH_TOKEN }}
      run: |
        python main.py
    
    - name: 显示运行结果
      if: always()
      run: echo "机器人运行完成！"

